name: Replicate KeyError Issue

on:
  push:
    branches:
      - develop
      - 'release-v**'
  pull_request:
    branches:
      - develop
      - 'release-v**'

jobs:
  replicate_issue:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt --upgrade
          pip install -r requirements/dev.txt --upgrade
          pip install -e .

      - name: Run tests in multiprocessing mode
        run: |
          export KOLIBRI_USE_WORKER_MULTIPROCESSING=True
          pytest kolibri/core/tasks/test/taskrunner/
